import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
import Cards from "~/components/Cards";
import type { Post, Response } from "~/types/types";

const Home: NextPage<Response> = ({ data }) => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="md:ml-[2.5vw] w-[95vw]">
                <div className=" mt-4 flex flex-col md:flex-row justify-center md:flex-wrap  items-center gap-8">
                    {data.message !== "Success" ? (
                        <>Something went wrong with server</>
                    ) : (
                        data.data.posts.map((post: Post) => {
                            return (
                                <>
                                    <Cards post={post} key={post.postId} />
                                </>
                            );
                        })
                    )}
                </div>
            </main>
        </>
    );
};

export async function getServerSideProps() {
    const data: Response = await fetch(
        "https://internship-service.onrender.com/videos?page=2"
    )
        .then((res) => {
            if (!res.ok) {
                throw new Error(res.statusText);
            }
            return res.json();
        })
        .then((res: Response) => {
            return res;
        });

    return {
        props: { data },
    };
}

export default Home;
